var imoveis = [
    {
        "tipo": 1,
        "endereco": "Rua Guaporé 526, Bairro Santa Rosa, Uberlândia - MG",
        "proprietarios": ["Guilherme Bartasson", "Maria Isabel"],
        "tipoTransacao": "Venda",
        "qtdQuartos": "2",
        "qtdSuites": "1",
        "qtdSalaEstar": "1",
        "qtdSalaJantar": "1",
        "vagasGaragem": "2",
        "area": "300 m²",
        "armarioEmbutido": "Sim",
        "descricao": "Descrição Teste",
        "andar": "N/A",
        "valorCondominio": "N/A",
        "portaria24horas": "N/A",
        "valorVenda": "R$ 320.000,00",
        "valorAluguel": "N/A",
        "valorRealVenda": "R$ 315.000,00",
        "valorRealAluguel": "N/A",
        "porcentagemImobiliaria": "30%",
        "dataInicioVenda": "02/03/2019",
        "dataInicioAluguel": "N/A",
        "dataFimVenda": "09/09/2019",
        "dataFimAluguel": "N/A",
        "vendido": "Sim",
        "alugado": "N/A",
        "funcionarioResponsavel": "Carlos da Cunha"
    },
    {
        "tipo": 2,
        "endereco": "Rua A 123, Bairro Estrela, Curralinho - MA",
        "proprietarios": ["Tonho da Couve"],
        "tipoTransacao": "Aluguel",
        "qtdQuartos": "2",
        "qtdSuites": "0",
        "qtdSalaEstar": "1",
        "qtdSalaJantar": "1",
        "vagasGaragem": "1",
        "area": "50 m²",
        "armarioEmbutido": "Não",
        "descricao": "Descrição Teste",
        "andar": "4",
        "valorCondominio": "R$ 320,00",
        "portaria24horas": "Sim",
        "valorVenda": "N/A",
        "valorAluguel": "R$ 800,00",
        "valorRealVenda": "N/A",
        "valorRealAluguel": "R$ 750,00",
        "porcentagemImobiliaria": "5%",
        "dataInicioVenda": "N/A",
        "dataInicioAluguel": "02/04/2018",
        "dataFimVenda": "N/A",
        "dataFimAluguel": "Atual",
        "vendido": "N/A",
        "alugado": "Sim",
        "funcionarioResponsavel": "Maria Clara"
    }
];